[package]
name = "axum_odbc"
version = "0.3.1"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide an ODBC-Api layer."
edition = "2021"
license = "MIT OR Apache-2.0 OR Zlib"
readme = "README.md"
documentation = "https://docs.rs/axum_odbc"
keywords = ["Axum", "Tower", "odbc", "odbc-api"]
repository = "https://github.com/AscendingCreations/AxumOdbc"

[features]
iodbc = ["odbc-api/iodbc"]

[dependencies]
axum-core = {version = "0.3.0-rc.2", git = "https://github.com/tokio-rs/axum.git" }
serde = "1.0.145"
serde_json = "1.0.86"
tokio = { version = "1.21.2", features = ["full"] }
async-trait = "0.1.57"
tracing = "0.1.37"
thiserror = "1.0.37"
http = "0.2.8"
odbc-api = "0.50.0"
lazy_static = "1.4"
crossbeam-queue = "0.3.6"

[dev-dependencies]
anyhow = "1.0.57"
axum = "0.6.0-rc.2"

