[package]
name = "axum_odbc"
version = "0.3.1"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide an ODBC-Api layer."
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/axum_odbc"
keywords = ["Axum", "Tower", "odbc", "odbc-api"]
repository = "https://github.com/AscendingCreations/AxumOdbc"

[features]
iodbc = ["odbc-api/iodbc"]

[dependencies]
axum-core = "0.2.7"
serde = "1.0.140"
serde_json = "1.0.82"
tokio = { version = "1.20.1", features = ["full"] }
async-trait = "0.1.56"
tracing = "0.1.35"
thiserror = "1.0.31"
http-body = "0.4.5"
http = "0.2.8"
tower-layer = "0.3.1"
tower-service = "0.3.2"
futures = "0.3.21"
bytes = "1.2.0"
odbc-api = "0.45.1"
lazy_static = "1.4"
crossbeam-queue = "0.3.6"

[dev-dependencies]
anyhow = "1.0.57"
axum = "0.5.14"

