[package]
name = "axum_odbc"
version = "0.4.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide an ODBC-Api layer."
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/axum_odbc"
keywords = ["Axum", "Tower", "odbc", "odbc-api"]
repository = "https://github.com/AscendingCreations/AxumOdbc"

[features]
iodbc = ["odbc-api/iodbc"]

[dependencies]
axum-core = "0.3.3"
serde = "1.0.159"
serde_json = "1.0.95"
tokio = { version = "1.27.0", features = ["full"] }
async-trait = "0.1.68"
tracing = "0.1.37"
thiserror = "1.0.40"
http = "0.2.8"
odbc-api = "0.55.0"
once_cell = "1.17.1"
crossbeam-queue = "0.3.8"

[dev-dependencies]
anyhow = "1.0.70"
axum = "0.6.12"

